server:
  port: 9080

spring:
  datasource:
#    platform: oracle
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    driver-class-name: oracle.jdbc.OracleDriver
    username: jojun2
    password: jojun9475
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto : none